### ISSUE TITLE
F3d file not created 

### ISSUE THREAD

**Issue by elfren** [WilkoV/Fusion360_ExportIt#20] opened 2020-09-18 18:47 UTC
No f3d files are not being created.  One of three linked step files are created.  One of two unlinked files are created.

Export Types: Step, F3d
Exclude Component: Component9
Exclude Links: Unchecked
Step Options: Structure
F3d Options: Structure

![ExportError](https://user-images.githubusercontent.com/9331987/93633754-4ffaa300-f9a4-11ea-9fe2-a67747527f74.JPG)
[CutterHead_FR188ZZ_Retro v4.zip](https://github.com/WilkoV/Fusion360_ExportIt/files/5247600/CutterHead_FR188ZZ_Retro.v4.zip)

**Comment by elfren** [comment] 2020-09-18 18:53
It looks like the initial search for components is failing to find all of them:
![ExportError2](https://user-images.githubusercontent.com/9331987/93634499-8dabfb80-f9a5-11ea-87f2-77e12e919ebb.JPG)

**Comment by WilkoV** [comment] 2020-09-18 19:48
I had a quick look at your file and I'm wondering why all the linked designs don't have a timeline. Did you used direct modeling or are those imported e.g. STEP files?

**Comment by elfren** [comment] 2020-09-18 20:02
They are imported from manufacturers as step files.

**Comment by WilkoV** [comment] 2020-09-18 20:15
- Okay - I've to check if the API can export step files as step files. Not sure about this.

**Comment by WilkoV** [comment] 2020-09-18 20:21
The Fusion file can not be created, because Fusion 360 can't export f3z files from within the desktop application. The same limitation is true for the API. The only way to export files with linked components is to either break the links before the export or by using the web interface.

**Comment by WilkoV** [comment] 2020-09-18 20:22
Okay - I've to check if the API can export step files as step files. Not sure about this.

> They are imported from manufacturers as step files.

**Comment by elfren** [comment] 2020-09-18 20:50
Other files seem to be finding all of the components including the imported step files and they are being exported.  There must be something in the initial component search in that file which is failing.

You may want to add the f3z comment to your documentation.

**Comment by WilkoV** [comment] 2020-09-18 20:57
I check it. I'll create some test files with step files, direct modelling and so on.  I haven't added it the documentation yet, because it's standard Fusion 360 behavior. But might be a good point.

**Comment by WilkoV** [comment] 2020-09-24 15:56
I'm trying to reproduce things and I'm not sure about this one. I wouldn't say that one is missing. IMO it shows to many, because Component9 doesn't have bodies and shouldn't be in the list. 
What components are missing in your opinion?

> It looks like the initial search for components is failing to find all of them:
> ![ExportError2](https://user-images.githubusercontent.com/9331987/93634499-8dabfb80-f9a5-11ea-87f2-77e12e919ebb.JPG)

**Comment by elfren** [comment] 2020-09-24 16:42
You're right.  I forgot the invisible components were not added to the list.  Component9 does only have a sketch.  For archiving purposes it would be much better to include all components.

**Comment by WilkoV** [comment] 2020-09-24 17:23
Archiving is a good point, but for this I have to modify a design and toggle this flag and even if I undo this, the document is changed for Fusion 360. This isn't idle, because a user might not want to store add-in configuration anymore. 
If this toggle is important to you, it would be great to create a dedicated issue marked as feature request and I'll implement it at a later point.
I've added some notes to the documentation regarding the linked components and I've added more information to the  summary report. I'll upload it later. I'm still testing it a bit.

**Comment by WilkoV** [comment] 2020-09-25 13:12
I've amended the documentation to clarify that Fusion Archive exports cannot contain linked components and that f3z files cannot be created with the API. 

Changes are pushed to branch 0.8.0. You can either switch to the branch or you can use one of the attached files. I merge it to to main later.
[ExportIt.tar.gz](https://github.com/WilkoV/Fusion360_ExportIt/files/5282940/ExportIt.tar.gz)
[ExportIt.zip](https://github.com/WilkoV/Fusion360_ExportIt/files/5282941/ExportIt.zip)

**Closed as completed** 2020-09-25 13:22 UTC
Labels: investigation
